[build]
  publish = "."
  command = "echo 'Static site - no build needed'"

# Configuración de funciones serverless
[functions]
  directory = "netlify/functions"

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirección para admin
[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200
